language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    - TESTER_PHP_BIN="php-cgi"
    - TESTER_PHP_BIN="hhvm"

matrix:
    allow_failure:
        - php: hhvm

    exclude:
        - php: 5.6
          env: TESTER_PHP_BIN="hhvm"
        - php: 7.0
          env: TESTER_PHP_BIN="hhvm"
        - php: 7.1
          env: TESTER_PHP_BIN="hhvm"
        - php: hhvm
          env: TESTER_PHP_BIN="php-cgi"

services:
    - mysql

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - composer global require "hirak/prestissimo"
    - mysql -u root -e 'CREATE DATABASE testbase;'

install:
    - composer install --no-interaction --prefer-dist

before_script:
    - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then
       coverage="-p phpdbg --coverage ./coverage.xml --coverage-src ./src/app";
       fi

script:
    - ./src/vendor/bin/phpcs ./src/app/ --standard=psr2 -spn
    - ./src/vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini -s ./tests/ $coverage

after_script:
    - >
        if [ "$coverage" != "" ]; then
        wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        && php coveralls.phar --verbose --config tests/.coveralls.yml
        || true; fi

after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
