language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    - TESTER_PHP_BIN="php-cgi"
    - TESTER_PHP_BIN="hhvm"

matrix:
    allow_failure:
        - php: hhvm

    exclude:
        - php: 5.6
          env: TESTER_PHP_BIN="hhvm"
        - php: 7.0
          env: TESTER_PHP_BIN="hhvm"
        - php: 7.1
          env: TESTER_PHP_BIN="hhvm"
        - php: hhvm
          env: TESTER_PHP_BIN="php-cgi"

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-source

script:
    - ./src/vendor/bin/phpcs ./src/app/ --standard=psr2 -spn
    - ./src/vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/php.ini -s ./tests/

after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
